
# 指定Eureka服务地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/,http://root:root@localhost:8762/eureka/
#指定服务的名称
spring:
  application:
    name: CONFIG
  cloud:
    config:
      server:
        git:
          #远程仓库的用户名
          username: ***
          #远程仓库的密码
          password: ***
          #远程仓库地址
          uri: https://gitee.com/sabiler/config-repo.git
          #默认拉取分支
          default-label: master
  rabbitmq:
    host: 192.168.25.150
    port: 5672
    username: test
    password: test
    virtual-host: /
server:
  port: 8090

management:
  endpoints:
    web:
      exposure:
        include: "*"